package org.crimsoncrips.craftorio.skill_tree;

public enum ModifierTarget {
    MULTIPLIER,
    ITEM_BASE_VALUE,
    ITEM_TAG_BASE_VALUE,
    CONTRACT_REFRESH_SPEED,
    EFFECT_TIMER_SPEED,
    PUNISHMENT_EFFECT_DURATION,
    EFFECT_DURATION,
    CLAIM_CHUNK_COST,
    BORDER_EXPANSION_COST,
    BETTER_CONTRACT_CHANCE,
    BETTER_EFFECT_CHANCE,
    SHOP_COST,
    CONTRACT_REFRESH_COST
}
